/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package play.twirl.gradle;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;

/**
 * A simple unit test for the 'play.twirl.gradle.greeting' plugin.
 */
class GradleTwirlPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("play.twirl.gradle.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
