name: Publish

on:
  push:
    branches: # Snapshots
      - 1.6.x
    tags: ["**"] # Releases

jobs:
  publish-artifacts:
    name: Publish / Artifacts
    uses: playframework/.github/.github/workflows/publish.yml@v4
    secrets: inherit
